# Generated by Django 4.2.6 on 2023-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0003_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raport',
            old_name='geocode',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='raport',
            name='lng',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raport',
            name='strada',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
